# docker-compose.yml

version: '3.9'

services:
  auth:
    build: ./auth
    command: uvicorn auth.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth:/app/auth
    ports:
      - 8001:8000
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=auth-db
      - DB_NAME=auth
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15-alpine
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth

  order:
    build: ./order
    command: uvicorn order.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./order:/app/order
    ports:
      - 8002:8000
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=order-db
      - DB_NAME=order
    depends_on:
      - order-db

  order-db:
    image: postgres:15-alpine
    expose:
      - 5432
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order